### ISSUE TITLE
As a epidemiologist, I can view articles clusters grouped and prioritized by outbreak, so I can interact with a set of articles simultaneously.

### ISSUE THREAD

**Issue by lucbelliveau** [PHACDataHub/foresight#3]
```[tasklist]
### Tasks
- [ ] https://github.com/PHACDataHub/foresight/issues/21
- [ ] https://github.com/PHACDataHub/foresight/issues/22
- [ ] https://github.com/PHACDataHub/foresight/issues/23
- [ ] https://github.com/PHACDataHub/foresight/issues/24
- [ ] https://github.com/PHACDataHub/foresight/issues/25
- [ ] https://github.com/PHACDataHub/foresight/issues/26
- [ ] https://github.com/PHACDataHub/foresight/issues/27
- [ ] https://github.com/PHACDataHub/foresight/issues/28
- [ ] https://github.com/PHACDataHub/foresight/issues/29
- [ ] https://github.com/PHACDataHub/foresight/issues/30
```
